<?php

namespace Addons\University\Controller;
use Home\Controller\AddonsController;

class UniversityController extends AddonsController{
    var $model;
    function _initialize() {
        $this->model = $this->getModel ( 'University' );
        parent::_initialize ();
    }
    // 通用插件的列表模型
    public function lists($model = null, $page = 0)
    {
        parent::lists($model, $page); // TODO: Change the autogenerated stub
    }
}
